### ISSUE TITLE
How you did your Data Augmentation

### ISSUE THREAD

**Issue by jerofad** [sara-kassani/ICIAR_Transfer_Learning_Global_Average_Pooling#1]
Thanks for sharing your work and approach to the problem.  

I see that you were able to augment the data to have 1155 samples per label ( from 75). Now my question is how did you do this. You mentioned you didn't use patch in your work, but instead downsample the image to `512 x512` image size. 

It would be so great if you can share the code for your data augmentation task to achieve this.

Thanks in advance

**Comment by sara-kassani** [comment]
Horizontal flip (HF) applied on:  75 original images -->result: 75 original + 75 HF_original --> Total **150**

Vertical flip (VF) applied on:  75 original images + 75 HF_original ----> 75 original + 75 VF_HF_original + 75_VF_original ---> Total 225 +75 HF_original = **300**

Brightness correction (BC) applied on: 75 original + 75 HF_original + 75 VF_original,  75 HF_VF_original ---> Total: 75 BC_original, 75 BC_HF_original + 75 BC_VF_original,  75 BC_HF_VF_original: **300** images

and you do the same with contrast correction, rotation and so on

**Comment by jerofad** [comment]
Thanks for your response.

**Comment by skykiny** [comment]
Hi,

I have a further question on how you get 1125 from 75. As you said by adding augmentation, it will be 150 (original+hf) + 150(vf on 150) + 300 (BC on previous 300) ..., it would not get exactly 1125. Then how did you get exactly 1125?

Also, you mentioned brightness/contract correction, what method did you use, is it a built-in function? For rotation, did you just rotate 90 degrees or random rotate it within some range?

If you could elaborate it a bit, I would really appreciate it. 
Thank you

Best,
Jingwei

**Comment by sara-kassani** [comment]
Original:75
HF (horizontal flip): 75_HF + 75_original  =150
Vf (vetrtical flip): 
75_VF + 
75_HF + 
75_original + 
75_HF_VF = 
300


Brightness Enhancement (BE): 
75_BE + 
75_BE_VF + 
75_BE_HF + 
75_BE_HF_ VF +
75_VF + 
75 HF + 
75 original + 
75_HF_VF = 600
****************************************************************************************
Data augmentation codes:

https://github.com/sara-kassani/Classification-of-histopathological-biopsy-images-/blob/master/data-augmentation.ipynb

**Comment by skykiny** [comment]
Thank you for your response!
